platform :ios, '5.0'
pod 'ReactiveCocoa', '1.8.1'
pod 'BButton', '~> 2.0.0'
pod 'WEPopover', '~> 0.0.1'
pod 'SDWebImage', '~> 3.3'
pod 'DACircularProgress', '~> 2.1.0'
#pod 'FlurrySDK', '~> 4.2.1'
#pod 'TestFlightSDK', '~> 1.3.0-beta.7'